import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/components/layouts/Navbar";
import Footer from "@/app/components/layouts/Footer";
import { UserProvider } from "./context/userContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Job Board",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <div className="App">
            <NavBar />
            {children}
            <Footer />
          </div>
        </UserProvider>
      </body>
    </html>
  );
}
