export const jobs = [
    {
      title: "Software Engineer",
      description: "Develop and maintain web applications using modern technologies.",
      jobType: "Full Time",
      jobCategory: "Software Development",
      company: "Technovation Inc.",
      location: "San Francisco, CA",
      salary: 120000,
      postedBy: "ObjectIdHere",
      datePosted: new Date("2024-09-05"),
    },
    {
      title: "Graphic Designer",
      description: "Create visually appealing graphics for marketing materials and websites.",
      jobType: "Part Time",
      jobCategory: "Design",
      company: "Creative Studios",
      location: "New York, NY",
      salary: 75000,
      postedBy: "AnotherObjectIdHere",
      datePosted: new Date("2024-09-10"),
    },
    {
      title: "Data Scientist",
      description: "Analyze large datasets to extract insights and trends.",
      jobType: "Full Time",
      jobCategory: "Data Science",
      company: "Analytics Solutions",
      location: "Austin, TX",
      salary: 135000,
      postedBy: "ObjectIdHere",
      datePosted: new Date("2024-09-02"),
    },
    {
      title: "Project Manager",
      description: "Lead and coordinate project teams to deliver successful outcomes.",
      jobType: "Full Time",
      jobCategory: "Project Management",
      company: "Agile Development",
      location: "Seattle, WA",
      salary: 110000,
      postedBy: "ObjectIdHere",
      datePosted: new Date("2024-08-28"),
    },
    {
      title: "Marketing Manager",
      description: "Develop and execute marketing strategies to increase brand awareness.",
      jobType: "Full Time",
      jobCategory: "Marketing",
      company: "BrandBoost",
      location: "Chicago, IL",
      salary: 95000,
      postedBy: "ObjectIdHere",
      datePosted: new Date("2024-09-03"),
    },
    {
      title: "UI/UX Designer",
      description: "Create intuitive and visually appealing user interfaces.",
      jobType: "Full Time",
      jobCategory: "Design",
      company: "User Experience Experts",
      location: "Boston, MA",
      salary: 90000,
      postedBy: "ObjectIdHere",
      datePosted: new Date("2024-09-07"),
    },
    {
      title: "Sales Representative",
      description: "Generate leads and close sales to meet revenue targets.",
      jobType: "Full Time",
      jobCategory: "Sales",
      company: "Growth Dynamics",
      location: "Denver, CO",
      salary: 80000,
      postedBy: "ObjectIdHere",
      datePosted: new Date("2024-09-01"),
    },
    {
      title: "Customer Support Specialist",
      description: "Provide excellent customer service and support.",
      jobType: "Full Time",
      jobCategory: "Customer Service",
      company: "HelpDesk Heroes",
      location: "Phoenix, AZ",
      salary: 75000,
      postedBy: "ObjectIdHere",
      datePosted: new Date("2024-09-06"),
    },
    {
      title: "Web Developer",
      description: "Build and maintain dynamic web applications.",
      jobType: "Full Time",
      jobCategory: "Software Development",
      company: "CodeCraft",
      location: "Dallas, TX",
      salary: 105000,
      postedBy: "ObjectIdHere",
      datePosted: new Date("2024-09-04"),
    },
    {
      title: "Accountant",
      description: "Manage financial records and prepare financial reports.",
      jobType: "Full Time",
      jobCategory: "Finance",
      company: "Fiscal Fitness",
      location: "Houston, TX",
      salary: 85000,
      postedBy: "ObjectIdHere",
      datePosted: new Date("2024-08-31"),
    },
  ];
  